server:
  port: 8080

spring:
  application:
    name: invoice-scanner-service

  flyway:
    baseline-on-migrate: true
    enabled: true
    schemas: iban_compliance
    out-of-order: true
    locations:
      - 'classpath:db/migration'
    default-schema: iban_compliance
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/invoice_scanner


  datasource:
    url: jdbc:postgresql://localhost:5432/invoice_scanner
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    com.example.invoicescanner: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method